# Change these first
owner: wexlerai # Your GitHub organization or username, where this repository lives
repo: wexler-status-page # The name of this repository

sites:
  - name: Landing Page
    url: https://www.wexler.ai
assignees: # Users to assign downtime issues (optional)
  - luisenriquecgongora

status-website:
  baseUrl: /wexler-status-page # where "repo" is your repository name
  name: Wexler Status Website
